export const sampleCategories = [
  {
    id: 1,
    slug: "essentials",
    label: "Gợi ý hằng ngày",
    name: "Thiết yếu mỗi ngày",
    description: "Những sản phẩm nhỏ, dễ chốt đơn nhanh và có khả năng mua lại cao.",
  },
  {
    id: 2,
    slug: "workspace",
    label: "Lớp bàn làm việc",
    name: "Nâng cấp góc làm việc",
    description: "Các món cho góc làm việc tại nhà giúp trình bày ảnh, nội dung và combo tốt hơn.",
  },
  {
    id: 3,
    slug: "travel",
    label: "Mang đi cuối tuần",
    name: "Đồ dùng du lịch",
    description: "Các sản phẩm tầm giá trung bình phù hợp cho khối nổi bật và chiến dịch khuyến mãi.",
  },
];

export const sampleProducts = [
  {
    id: 1,
    categoryId: 3,
    slug: "linen-carryall",
    name: "Túi xách vải lanh",
    category: "Du lịch",
    description: "Túi mềm phom đứng cho những chuyến đi cuối tuần, việc vặt và mang theo hằng ngày.",
    price: 780000,
    featured: true,
    badge: "Bán chạy",
    sku: "GET-001",
    inventory: 18,
    gradient: "linear-gradient(135deg, #14323e, #4d7787)",
    imageUrl: null,
    highlights: ["Quai phủ sáp", "Ngăn máy tính 13 inch", "Lớp lót chống thấm nhẹ"],
  },
  {
    id: 2,
    categoryId: 1,
    slug: "stoneware-mug-set",
    name: "Bộ ly gốm nung",
    category: "Thiết yếu hằng ngày",
    description: "Hai ly tông trung tính cho buổi sáng, quà tặng và góc bếp.",
    price: 340000,
    featured: true,
    badge: "Combo",
    sku: "GET-002",
    inventory: 42,
    gradient: "linear-gradient(135deg, #8d3615, #d9906f)",
    imageUrl: null,
    highlights: ["Men hoàn thiện thủ công", "Xếp chồng gọn", "An toàn với máy rửa chén"],
  },
  {
    id: 3,
    categoryId: 2,
    slug: "felt-desk-mat",
    name: "Tấm lót bàn nỉ",
    category: "Nâng cấp góc làm việc",
    description: "Điểm nhấn gọn gàng cho bàn phím, sổ tay và ảnh chụp ngày mở bán.",
    price: 460000,
    featured: true,
    badge: "Mới về",
    sku: "GET-003",
    inventory: 27,
    gradient: "linear-gradient(135deg, #3b4c28, #94a36c)",
    imageUrl: null,
    highlights: ["Bề mặt pha len merino", "Rãnh luồn cáp", "Cuộn gọn dễ mang"],
  },
  {
    id: 4,
    categoryId: 1,
    slug: "glass-storage-trio",
    name: "Bộ hũ thủy tinh 3 món",
    category: "Thiết yếu hằng ngày",
    description: "Hộp đựng nhà bếp lên hình đẹp và bán tốt theo combo.",
    price: 520000,
    featured: true,
    badge: "Gian bếp",
    sku: "GET-004",
    inventory: 31,
    gradient: "linear-gradient(135deg, #614134, #c08b72)",
    imageUrl: null,
    highlights: ["Nắp kín hơi", "Kích thước lồng nhau", "Bao bì sẵn kệ"],
  },
  {
    id: 5,
    categoryId: 2,
    slug: "canvas-laptop-sleeve",
    name: "Túi chống sốc vải bố cho máy tính xách tay",
    category: "Nâng cấp góc làm việc",
    description: "Bao đựng có đệm cho trang sản phẩm tối giản và bán kèm hiệu quả.",
    price: 640000,
    featured: false,
    badge: "Chọn lọc",
    sku: "GET-005",
    inventory: 14,
    gradient: "linear-gradient(135deg, #362d4a, #8d78be)",
    imageUrl: null,
    highlights: ["Nắp nam châm", "Lót nhung mềm", "Vừa thiết bị 14 inch"],
  },
  {
    id: 6,
    categoryId: 3,
    slug: "weekend-packing-cubes",
    name: "Bộ túi chia đồ cuối tuần",
    category: "Du lịch",
    description: "Túi nén giúp tăng doanh thu bán kèm và khách dễ hiểu công năng.",
    price: 390000,
    featured: false,
    badge: "Tiện ích",
    sku: "GET-006",
    inventory: 55,
    gradient: "linear-gradient(135deg, #264653, #52b6ab)",
    imageUrl: null,
    highlights: ["Bộ 3 món", "Mặt lưới thoáng", "Giặt máy được"],
  },
];

export const stackHighlights = [
  {
    label: "Giao diện",
    title: "App Router của Next.js",
    description: "Server Components, Route Handlers và một đích triển khai duy nhất.",
  },
  {
    label: "Máy chủ",
    title: "Tuyến API trong cùng kho mã",
    description: "Giữ logic sản phẩm, đơn hàng và quản trị gần giao diện cho tới khi cần tách quy mô.",
  },
  {
    label: "Cơ sở dữ liệu",
    title: "MySQL đặt ngoài",
    description: "Dùng gói MySQL được quản lý miễn phí và truyền thông tin kết nối qua biến môi trường.",
  },
];

export const launchChecklist = [
  {
    title: "Hoàn thiện cấu trúc dữ liệu",
    description: "Chạy migration SQL khởi tạo và chốt các trường đầu tiên cho sản phẩm và đơn hàng.",
  },
  {
    title: "Thêm xác thực quản trị",
    description: "Bảo vệ khu quản trị trước khi đưa tồn kho và dữ liệu đơn hàng thật vào.",
  },
  {
    title: "Làm trang thanh toán",
    description: "Bắt đầu với COD hoặc chuyển khoản để bản đầu tiên không bị chặn bởi cổng thanh toán.",
  },
];

export const adminTracks = [
  {
    label: "Nội dung",
    title: "Quản lý danh mục",
    description: "Thêm, sửa, xóa sản phẩm, danh mục, tham chiếu hình ảnh và cờ sản phẩm nổi bật.",
    items: ["Tạo form sản phẩm", "Chiến lược tải ảnh lên", "Luồng cập nhật tồn kho"],
  },
  {
    label: "Vận hành",
    title: "Xử lý đơn hàng",
    description: "Quản lý trạng thái cơ bản là đủ cho bản phát hành vận hành thật đầu tiên.",
    items: ["Liệt kê đơn mới", "Đánh dấu đã thanh toán hoặc giao", "Theo dõi ghi chú khách hàng"],
  },
  {
    label: "Hạ tầng",
    title: "Lộ trình triển khai",
    description: "Giữ cấu hình máy cục bộ và môi trường triển khai đồng nhất ngay từ đầu.",
    items: ["Kho GitHub", "Biến môi trường Netlify", "Sao lưu MySQL"],
  },
];
